services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMjQ2ZjYyZDIwMmQ0N2RlZmExNjU1OTI1M2YwZGJmNTgiLCJzIjoiazFacGwwc0VTV1lrREMrYm1SMmdPZXNCa2NmeUt6YllFUVJFRC9tNVNXND0iLCJ0IjoiNGI2YzMzZDQtNTcwMi00ZWZkLWJjODgtODAyYmZiMWI1MGM1In0=
    volumes:
      - ./cloudflare-config.yml:/etc/cloudflared/config.yml
      - /home/picking-server/.cloudflared/4b6c33d4-5702-4efd-bc88-802bfb1b50c5.json:/etc/cloudflared/4b6c33d4-5702-4efd-bc88-802bfb1b50c5.json
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=https://api.smartpicker.au
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - FRONTEND_URL=https://smartpicker.au
    ports:
      - "5033:5033"
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge